### ISSUE TITLE
URL to contact page is a 404

### ISSUE THREAD

**Issue by MarcusMorba** [ricardobalk/www#16]
File not found: https://ricardobalk.nl/contact

**Comment by ellipticcurv3** [comment]
Thanks for the heads up,

I will work on it this evening. In the mean time, please contact me via Keybase (keybase.io/ellipticcurv3), where people could audit my online identities and could have a secure, end-to-end encrypted conversation with me.

-------- Oorspronkelijk bericht --------
Aan 31 dec. 2019 11:18, Marcus Morba wrote:

**Comment by ellipticcurv3** [comment]
8d9576eb09d16440aef28b90f876f63bfacf3dc2 47307711faa05ac41c2d569f16a3f44705bb0300 d051dd23e6b856fda5b1b0bf89ddcf79632cfa89

So what I did to fix it,

Instead of adding a full-featured contact page, for now I changed the contact button on the home page to simple redirection to places to contact me directly. The main benefit is that it will use the users' default applications, for example when clicking on the mail icon. I also added `title` attributes, so people know where they are going when clicking on them.

English - Light theme

![image](https://user-images.githubusercontent.com/14904229/71755360-892cca80-2e8a-11ea-954a-3b03268ecdff.png)

Dutch - Light theme

![image](https://user-images.githubusercontent.com/14904229/71755380-a19ce500-2e8a-11ea-8283-0eceace750da.png)

English - Dark theme

![image](https://user-images.githubusercontent.com/14904229/71755376-99dd4080-2e8a-11ea-97cb-2d000367a1db.png)

Dutch - Dark theme

![image](https://user-images.githubusercontent.com/14904229/71755389-aa8db680-2e8a-11ea-9c4e-f3d3df5ee264.png)
